name: Deploy Azure APIM Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev      

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create .env file from environment variables
      run: |
        cat > .env << EOF
        # The Azure location to deploy to
        AZURE_LOCATION=${{ vars.AZURE_LOCATION }}
        
        # A suffix for naming
        RESOURCE_NAME_PREFIX=${{ vars.RESOURCE_NAME_PREFIX }}
        
        # A tag that will be included in the naming
        ENVIRONMENT_TAG=${{ vars.ENVIRONMENT_TAG }}
        
        # Optional 3 character random string to ensure deployments are unique
        RANDOM_IDENTIFIER=${{ vars.RANDOM_IDENTIFIER }}
        
        #Address space VNET
        VNETADDRESSPREFIX="${{ vars.VNETADDRESSPREFIX }}"
        
        #Address subset of IP APIM Subbet
        APIMADDRESSPREFIX="${{ vars.APIMADDRESSPREFIX }}"
        
        #Address subset of IP Private Endpoint
        PRIVATEENDPOINTADDRESSPREFIX="${{ vars.PRIVATEENDPOINTADDRESSPREFIX }}"
        
        #Resource Group Name
        RESOURCE_GROUP_NAME=${{ vars.RESOURCE_GROUP_NAME }}
        
        #APIM Custom Domain Name
        APIM_CUSTOM_DOMAIN_NAME=${{ vars.APIM_CUSTOM_DOMAIN_NAME  }}
        EOF
        echo "Created .env file with environment variables"
        cat .env

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Completar con los pasos adicionales del workflow
    - name: Deploy Azure Infrastructure
      run: |
        chmod +x ./IaC/Scripts/deploy-apim-baseline.sh
        ./IaC/Scripts/deploy-apim-baseline.sh